# Site settings
title: WorldMaker.net
email: me@worldmaker.net
description: > # this means to ignore newlines until "baseurl:"
  Max Battcher's personal blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://worldmaker.net" # the base hostname & protocol for your site
twitter_username: WorldMaker
github_username:  WorldMaker
encoding: utf-8
paginate: 50
paginate_path: /archive:num/
permalink: pretty
exclude:
 - _archive
include:
 - .well-known

# Build settings
markdown: kramdown

# Plugins
plugins:
 - jekyll-redirect-from
